### ISSUE TITLE
Unknown function used in 'performance_testing.py'

### ISSUE THREAD

**Issue by AlkisPis** [avikor/constraint_satisfaction_problems#1]
The file 'performance_testing.py' contains the following line (2 times):

    solution = getattr(csp, constraint_solver)(problem, *args, **kwargs)

The function 'getattr()' is nowhere to be found in the whole package!

**Comment by avikor** [comment]
Hi, it's been several years since I last written anything in Python, so hopefully I'm not out of my depth. 
If I remember correctly I think I'm calling this function - 
https://docs.python.org/3/library/functions.html#getattr
